---
# roles/odoo/defaults/main.yml

odoo_hostname:    "erp01.adlin.lab"
odoo_fqdn_public: "erp.adlin.lab"
odoo_version:     "19.0"

# Dépôt nightly officiel Odoo (RPM)
odoo_repo_url: "https://nightly.odoo.com/{{ odoo_version }}/nightly/rpm/"

# PostgreSQL — peer authentication (pas de mot de passe)
# L'utilisateur système odoo = rôle PostgreSQL odoo
odoo_db_name: "odoo"
odoo_db_user: "odoo"

# Workers multi-process (dimensionnement pour 2 vCPUs)
odoo_workers:          4
odoo_max_cron_threads: 2
odoo_longpolling_port: 8072

# Chemins
odoo_config_file: "/etc/odoo/odoo.conf"
odoo_log_file:    "/var/log/odoo/odoo.log"
odoo_data_dir:    "/var/lib/odoo"

# LDAP — svc_odoo (ldap_bind_password_odoo défini dans group_vars/all/vars.yml)
odoo_ldap_bind_dn:   "uid=svc_odoo,cn=sysaccounts,cn=etc,{{ freeipa_base_dn }}"
odoo_ldap_bind_pass: "{{ ldap_bind_password_odoo }}"
odoo_ldap_base:      "{{ freeipa_base_dn }}"
odoo_ldap_filter:    "(memberOf=cn=odoo_users,cn=groups,cn=accounts,{{ freeipa_base_dn }})"
