---
# 8069/tcp — UI Odoo + API XML-RPC/JSON-RPC (depuis proxy01 uniquement)
# 8072/tcp — workers longpolling (depuis proxy01 uniquement)

- name: "firewalld | Autoriser Odoo UI (8069/tcp) pour proxy01"
  ansible.posix.firewalld:
    rich_rule: "rule family='ipv4' source address='10.10.10.100' port port='8069' protocol='tcp' accept"
    permanent: true
    state: enabled
    immediate: true

- name: "firewalld | Autoriser Odoo longpolling (8072/tcp) pour proxy01"
  ansible.posix.firewalld:
    rich_rule: "rule family='ipv4' source address='10.10.10.100' port port='8072' protocol='tcp' accept"
    permanent: true
    state: enabled
    immediate: true
