---
galaxy_info:
  role_name: rocketchat
  author: "Frédéric"
  description: "Rocket.Chat 8.x via Docker Compose avec sync LDAP FreeIPA"
  license: "MIT"
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
