---
# roles/nextcloud/tasks/ipa_service.yml
#
# Crée le principal HTTP/cloud01.adlin.lab dans FreeIPA.
# Requis pour que certmonger puisse demander et renouveler le certificat TLS Apache.

- name: "ipa_service | Créer le principal HTTP pour cloud01"
  freeipa.ansible_freeipa.ipaservice:
    ipaadmin_password: "{{ ipa_admin_password }}"
    name: "HTTP/{{ nextcloud_hostname }}"
    state: present
  delegate_to: ipa01.adlin.lab
