---
galaxy_info:
  role_name: nextcloud
  author: "Frédéric"
  description: "Déploie Nextcloud 33 sur Rocky Linux 9 avec FreeIPA LDAP et certmonger TLS"
  license: "MIT"
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
