---
galaxy_info:
  role_name: nextcloud
  author: fred
  description: "Déploie Nextcloud 33 sur Rocky Linux 9 avec FreeIPA LDAP et certmonger TLS"
  min_ansible_version: "2.14"
  platforms:
    - name: Rocky
      versions:
        - "9"
dependencies: []
