---
# roles/freeipa_server/tasks/main.yml

- name: "Freeipa_server | Hostname"
  ansible.builtin.import_tasks: hostname.yml
  tags: [freeipa_server, hostname]

- name: "Freeipa_server | Firewalld — ports FreeIPA"
  ansible.builtin.import_tasks: firewalld.yml
  tags: [freeipa_server, firewalld]

- name: "Freeipa_server | Installation FreeIPA server"
  ansible.builtin.import_tasks: ipaserver.yml
  tags: [freeipa_server, install]

- name: "Freeipa_server | Comptes de service LDAP"
  ansible.builtin.import_tasks: service_accounts.yml
  tags: [freeipa_server, ldap, service_accounts]

- name: "Freeipa_server | Groupes applicatifs"
  ansible.builtin.import_tasks: app_groups.yml
  tags: [freeipa_server, ldap, groups]
