---
galaxy_info:
  role_name: freepbx
  author: "Frédéric"
  description: "FreePBX 17 + Asterisk 21 sur Debian 12, avec enrollment FreeIPA client"
  license: "MIT"
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies: []
