---
galaxy_info:
  role_name: freepbx
  author: adlin
  description: "FreePBX 17 + Asterisk 21 sur Debian 12, avec enrollment FreeIPA client"
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies: []
